source=~/.config/hypr/configs/settings.conf
source=~/.config/hypr/configs/visuals.conf
source=~/.config/hypr/configs/keybindings.conf
source=~/.config/hypr/configs/windowrules.conf
source=~/.config/hypr/custom/custom.conf

