env = QT_QPA_PLATFORMTHEME,hyprqt6engine
env = XDG_MENU_PREFIX,arch-

exec-once = qs -c noctalia-shell
exec-once = systemctl --user start hyprpolkitagent
exec-once = udiskie

general { 
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}

input {
    kb_layout = us
    kb_variant = intl

    follow_mouse = 2
    float_switch_override_focus = 0

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

cursor {
    no_warps = true
}
